name: CI (Jira on-premises)
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn clean compile test --file pom.xml
      - name: Submit results to Xray
        run: |
          token=$(curl -H "Content-Type: application/json" -X POST --data '{ "client_id": "${{ secrets.jira_username }}","client_secret": "${{ secrets.jira_password }}" }' https://xray.cloud.xpand-it.com/api/v1/authenticate|tr -d '"')
          curl -H "Content-Type: applicaion/xml" -X POST -H "Authorization: Bearer $token" --data @"target/surefire-reports/TEST-com.company.DemoTest.xml" https://xray.cloud.xpand-it.com/api/v2/import/execution/junit?projectKey=DEMO             
        
