name: CI (Jira on-premises example)
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn clean compile test --file pom.xml
      - name: Submit results to Xray
        env:
          JIRA_SERVER_URL: ${{ secrets.jira_server_url }}
          JIRA_USERNAME: ${{ secrets.jira_username }}
          JIRA_PASSWORD: ${{ secrets.jira_password }}
        run: |
          token=$(curl -H "Content-Type: application/json" -X POST --data '{ "client_id": "$JIRA_USERNAME","client_secret": "$JIRA_PASSWORD" }' https://xray.cloud.xpand-it.com/api/v1/authenticate|tr -d '"')
          curl -H "Content-Type: text/xml" -X POST -H "Authorization: Bearer $token"  --data @"target/surefire-reports/TEST-com.company.DemoTest" https://xray.cloud.xpand-it.com/api/v2/import/execution/junit?projectKey=DEMO             
        
